# -*- mode: ruby -*-
# vi: set ft=ruby :
## I am using Vagrant to create and Destory VM in Virtual Box
# You need Virtual Box and Vargrant Intsalled in your Computer to proceed to further steps

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

config.vm.define "mysql1.local" do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "private_network", ip: "192.168.0.9"
    config.vm.hostname = "mysql1.local"  
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "database.yml"
      ansible.verbose        = true
    end
  end

  config.vm.define "backup.local" do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "private_network", ip: "192.168.0.10"
    config.vm.hostname = "backup1.local"
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "sqlbackup.yml"
      ansible.verbose        = true
    end
  end

end
