---
db_hostname_short: mysql1
db_hostname: "{{ db_hostname_short }}.local"
db_ip: 192.168.0.10
backup_hostname_short: backup
backup_hostname: "{{ backup_hostname_short }}.local"
backup_ip: 192.168.0.11

