---
- name: configure local DNS
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=644

- name: copy id_rsa to  to enable acccess to backup server
  copy: src=id_rsa dest=/home/vagrant/.ssh/id_rsa owner=vagrant group=vagrant mode=600

- name: create /root/.ssh dir
  file: path=/root/.ssh state=directory owner=root group=root mode=700

- name: copy id_rsa for root to enable acccess to backup server
  #these authorized_keys are created and pleaced in files folder and copy them where you needed
  copy: src=id_rsa dest=/root/.ssh/id_rsa owner=root group=root mode=600

- name: Set authorized key for root
  #authorized_key: user=root state=present key="{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"
  copy: src=id_rsa.pub dest=/root/.ssh/authorized_keys owner=root group=root mode=600


